#!/bin/sh

# See https://habr.com/ru/articles/833564/ for more details

# opkg update
# opkg install iptables ipset curl gzip grep git-http
# cd /opt && mkdir git && cd git
# git clone https://github.com/bol-van/zapret.git && cd zapret
# ./install_bin.sh
# cd /opt/etc/init.d/
# vi S97tpws

## <copy all the content below>

# chmod +x /opt/etc/init.d/S97tpws
# /opt/etc/init.d/S97tpws start

SCRIPT=/opt/git/zapret/tpws/tpws
PIDFILE=/var/run/tpws.pid
HOSTLISTFILE=/opt/git/zapret/hostlist.txt
ARGS="--daemon --bind-addr 192.168.1.1 --port 999 --disorder --tlsrec=sni --split-pos=2 --pidfile $PIDFILE --hostlist $HOSTLISTFILE"

start() {
  if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)"; then
    echo 'Service TPWS is already running' >&2
    return 1
  fi
  $SCRIPT $ARGS
  iptables -t nat -A PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 999
  iptables -t nat -A PREROUTING -i br0 -p tcp --dport 443 -j REDIRECT --to-port 999
  echo 'Started TPWS service'
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 "$(cat $PIDFILE)"; then
    echo 'Service TPWS is not running' >&2
    return 1
  fi
  echo 'Stopping TPWS service...'
  kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
  iptables -t nat -D PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 999
  iptables -t nat -D PREROUTING -i br0 -p tcp --dport 443 -j REDIRECT --to-port 999
}

status() {
  if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)"; then
    echo 'Service TPWS is running'
  else
    echo 'Service TPWS is stopped'
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
